name: Auto Merge

on:
  pull_request:
    types: [labeled, opened, reopened]

jobs:
  merge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Merge Pull Request
        uses: peter-evans/merge-pull-request@v2
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge
